language: python
python:
  - 2.6
  - "2.7_with_system_site_packages"
  - 3.1
  - "3.2_with_system_site_packages"
before_install:
    - sudo apt-get update
install:
  - pip install numpy
  - pip install matplotlib
  - pip install scipy
notifications: 
  email: false